### ISSUE TITLE
[QUERY] WebApps/Functions authsetting configuration parameters

### ISSUE THREAD

**Issue by eosfor** [Azure/azure-libraries-for-net#1033]
**Query/Question**
Colleagues, we use the feature described [here](https://docs.microsoft.com/en-us/azure/templates/microsoft.web/2019-08-01/sites/config-authsettings), as below. The question is, is something like that supported as part of the Fluent library? Unfortunately, I did not find any samples for such things.

```yaml
...
        {
          "name": "authsettings",
          "apiVersion": "2018-02-01",
          "type": "config",
          "dependsOn": [
            "[resourceId('Microsoft.Web/sites', parameters('appName'))]"
          ],
          "properties": {
            "enabled": true,
            "defaultProvider": "AzureActiveDirectory",
            "clientId": "[parameters('pmaClientId')]"
          }
        }
...
```
